name: Download popular images from nasa

on: 
  push:
    branches:
      - save-images-from-nasa

jobs:
  read-json:
    name: Reading json file and building parallels
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read json file
        if: ${{ success() }}
        id: readjson
        uses: antifree/json-to-variables@v1.2.0
        with:
          filename: 'dates.json'
          prefix: 'dates'

      - name: Set matrix for jobs
        if: ${{ success() }}
        id: set_matrix
        run: |
          vars=($(env | grep '^dates_dates_' | awk -F'=' '{print $2}'))
          matrix_json=$(echo "[\"$(echo ${vars[*]} | sed 's/ /\", \"/g')\"]")
          echo "matrix=$matrix_json" >> "$GITHUB_OUTPUT"

  process-images:
    name: Image processing
    runs-on: ubuntu-latest
    needs: read-json
    strategy:
      matrix:
        dates: ${{ fromJson(needs.read-json.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Evaluate image cache
        id: cache-img
        uses: actions/cache@v4
        env:
          cache-name: cache-img
        with:
          path: img-${{ matrix.dates }}.*
          key: cache-img-${{ matrix.dates }} 
          restore-keys: |
            cache-img-

      - name: Execute GET request if cache does not exist
        id: fetch_image
        if: ${{ steps.cache-img.outputs.cache-hit != 'true' }}
        run: |
          set -e
          response=$(curl -s -X GET "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.dates }}")
          if echo "$response" | jq -e '.code' > /dev/null; then
            msg=$(echo "$response" | jq -r '.msg')
            echo "Error en la consulta: $msg" >&2
            exit 1
          fi
          image_url=$(echo "$response" | jq -r '.url')
          echo "image_url=$image_url" >> $GITHUB_ENV
          extension="${image_url##*.}"
          echo "image_extension=$extension" >> $GITHUB_ENV

      - name: Download image from URL 
        if: ${{ steps.cache-img.outputs.cache-hit != 'true' && success() }}
        uses: minituff/save-image@v1.4
        with:
          url: ${{ env.image_url }}
          imagePath: 'img-${{ matrix.dates }}.${{ env.image_extension }}'

      - name: Upload image artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: img-${{ matrix.dates }}
          path: img-${{ matrix.dates }}.*