name: save images from nasa

on: 
  push:
    branches:
      - save-images-from-nasa

jobs:
  read-json:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read json file
      id: readjson
      uses: antifree/json-to-variables@v1.2.0
      with:
        filename: 'dates.json'
        prefix: 'dates'

    - name: Count environment variables
      id: count_vars
      run: |
        vars=()
        for var in $(env | grep '^dates_dates_' | cut -d'=' -f1); do
          vars+=("${!var}")
        done
        echo "vars=${vars[*]}" >> $GITHUB_ENV

    - name: Set matrix for jobs
      id: set_matrix
      run: |
        matrix_json=$(echo "[\"$(echo ${vars[*]} | sed 's/ /\", \"/g')\"]")
        echo "matrix=$matrix_json" >> "$GITHUB_OUTPUT"

  process-images:
    runs-on: ubuntu-latest
    needs: read-json
    strategy:
      matrix:
        dates: ${{ fromJson(needs.read-json.outputs.matrix) }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verificar si ya existe la respuesta
      id: check_cache
      run: |
        CACHE_FILE="img-${{ matrix.dates }}.json"
        if [ -f "$CACHE_FILE" ]; then
          echo "Respuesta en caché encontrada: $CACHE_FILE"
          response=$(cat "$CACHE_FILE")
          echo "response=$response" >> $GITHUB_ENV
        else
          echo "No se encontró respuesta en caché."
          echo "response=null" >> $GITHUB_ENV
        fi  

    - name: Hacer una petición GET si no hay caché
      id: fetch_image
      if: steps.check_cache.outputs.response == 'null'
      run: |
        echo "Consultando la fecha: ${{ matrix.dates }}"
        response=$(curl -s -X GET "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.dates }}")
        echo "Respuesta: $response"
        
        # Verificar si la respuesta contiene un error
        if [[ "$response" == *'"url":null'* ]]; then
          echo "La respuesta del API no contiene una URL válida."
          echo "response=null" >> $GITHUB_ENV
        else
          echo "$response" > "$CACHE_FILE"  # Guardar respuesta en caché
          echo "response=$response" >> $GITHUB_ENV
        fi

    - name: Extraer URL de la imagen
      id: extract_image_url
      run: |
        image_url=$(echo "$response" | jq -r '.url')
        echo "image_url=$image_url" >> $GITHUB_ENV
        echo "URL de la imagen: $image_url"

    - name: Save image from URL 
      uses: minituff/save-image@v1.4
      with:
        url: ${{ env.image_url }}
        imagePath: 'img-${{ matrix.dates }}.jpg'

    - name: Upload JSON artifact
      uses: actions/upload-artifact@v4
      with:
        name: img-${{ matrix.dates }}
        path: img-${{ matrix.dates }}.jpg
