name: save images from nasa

on: 
  push:
    branches:
      - save-images-from-nasa

jobs:
  read-json:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read json file
      id: readjson
      uses: antifree/json-to-variables@v1.2.0
      with:
        filename: 'dates.json'
        prefix: 'dates'

    - name: Count environment variables
      id: count_vars
      run: |
        vars=()
        for var in $(env | grep '^dates_dates_' | cut -d'=' -f1); do
          vars+=("$var")
        done
        echo "vars=${vars[*]}" >> $GITHUB_ENV

    - name: Set matrix for jobs
      id: set_matrix
      run: |
        matrix_json=$(echo "[\"$(echo ${vars[*]} | sed 's/ /\", \"/g')\"]")
        echo "matrix=$matrix_json" >> "$GITHUB_OUTPUT"

  process-images:
    runs-on: ubuntu-latest
    needs: read-json
    strategy:
      matrix:
        dates: ${{ fromJson(needs.read-json.outputs.matrix) }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print matrix
      run: |
        echo "Matrix values: ${{ matrix.dates }}"
