name: save images from nasa

on: 
  push:
    branches:
      - save-images-from-nasa

jobs:
  read-json:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read json file
      id: readjson
      uses: antifree/json-to-variables@v1.2.0
      with:
        filename: 'dates.json'
        prefix: 'dates'

    - name: Use extracted value
      run: | 
        echo "Extracted values are: ${{ env.dates_dates_0 }}"

    - name: Count environment variables
      id: count_vars
      run: |
        count=0
        vars=()
        for var in $(env | grep '^dates_dates_' | cut -d'=' -f1); do
          vars+=("$var")
          count=$((count + 1))
        done
        echo "Total environment variables: $count"
        echo "vars=${vars[*]}" >> $GITHUB_ENV

    - name: Set matrix for jobs
      id: set_matrix
      run: |
        echo "matrix=[${vars[*]}]" >> "$GITHUB_OUTPUT"

  process-images:
    runs-on: ubuntu-latest
    needs: read-json
    strategy:
      matrix:
        dates: ${{ fromJson(needs.read-json.outputs.matrix) }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print matrix
      run: |
        echo "Matrix values: ${{ matrix.dates }}"

    - name: Process image for date
      run: |
        echo "Processing images for date: ${{ matrix.dates }}"
